name: Deploy CAI book to Azure Static Web Apps

on:
  push:
    branches: [ main ]     # vaihda 'master' jos käytössä
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) Quarto CLI
      - uses: quarto-dev/quarto-actions/setup@v2

      # 2) Rakenna kirja -> _book/
      - run: quarto render

      # 3) Deploy _book/ SWA:han (ei Oryx-buildia)
      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # >>> VAIHDA TÄMÄ SALAISUUDEN NIMI VASTAAMAAN REPOSSA OLEVAA <<<
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: "_book"
          skip_app_build: true
